name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - run: npx keycloakify
        env:
          XDG_CACHE_HOME: '/home/runner/.cache/yarn'

  create_github_release:
    runs-on: ubuntu-latest

    # We create a release only if the version have been upgraded and we are on a default branch
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - run: npx keycloakify
        env:
          XDG_CACHE_HOME: '/home/runner/.cache/yarn'
      - run: mv build_keycloak/target/retrocompat-*.jar retrocompat-keycloak-theme.jar
      - run: mv build_keycloak/target/*.jar keycloak-theme.jar
      - uses: softprops/action-gh-release@v1
        with:
          name: Release

          target_commitish: \${{ github.head_ref || github.ref }}
          generate_release_notes: true
          draft: false
          files: |
            retrocompat-keycloak-theme.jar
            keycloak-theme.jar
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
